workflows:
    dart-command-line-tool:
        name: Dart Command Line Tool
        environment:
            flutter: 1.22.0
        triggering:
          events:
            - tag
          branch_patterns:
            - pattern: '*master*'
              include: true
              source: true
        scripts:
            - dart compile --help